from __future__ import annotations

from typing import Dict

# Default ASS style values used when rendering subtitles.
DEFAULT_STYLE_VALUES: Dict[str, str] = {
    "Name": "Subtitle",
    "Fontname": "Microsoft YaHei",
    "Fontsize": "48",
    "PrimaryColour": "&H00FFFFFF",
    "SecondaryColour": "&H000000FF",
    "OutlineColour": "&H00000000",
    "BackColour": "&H64000000",
    "Bold": "0",
    "Italic": "0",
    "Underline": "0",
    "StrikeOut": "0",
    "ScaleX": "100",
    "ScaleY": "100",
    "Spacing": "0",
    "Angle": "0",
    "BorderStyle": "1",
    "Outline": "3",
    "Shadow": "0",
    "Alignment": "2",
    "MarginL": "60",
    "MarginR": "60",
    "MarginV": "45",
    "Encoding": "1",
}

# Normalised lookup table for style key aliases mapping to ASS canonical names.
STYLE_KEY_ALIASES: Dict[str, str] = {
    "name": "Name",
    "stylename": "Name",
    "fontname": "Fontname",
    "font": "Fontname",
    "fontfamily": "Fontname",
    "font_size": "Fontsize",
    "fontsize": "Fontsize",
    "primarycolour": "PrimaryColour",
    "primarycolor": "PrimaryColour",
    "secondarycolour": "SecondaryColour",
    "secondarycolor": "SecondaryColour",
    "outlinecolour": "OutlineColour",
    "outlinecolor": "OutlineColour",
    "backcolour": "BackColour",
    "backcolor": "BackColour",
    "bold": "Bold",
    "italic": "Italic",
    "underline": "Underline",
    "strikeout": "StrikeOut",
    "scalex": "ScaleX",
    "scaley": "ScaleY",
    "spacing": "Spacing",
    "angle": "Angle",
    "borderstyle": "BorderStyle",
    "outline": "Outline",
    "shadow": "Shadow",
    "alignment": "Alignment",
    "marginl": "MarginL",
    "marginleft": "MarginL",
    "marginr": "MarginR",
    "marginright": "MarginR",
    "marginv": "MarginV",
    "margintop": "MarginV",
    "encoding": "Encoding",
}
