"""autogenerate: sync models

Revision ID: 349a1a8ebac7
Revises: 7bea168f7920
Create Date: 2025-10-17 01:08:06.708590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349a1a8ebac7'
down_revision = '7bea168f7920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
