"""initial migration

Revision ID: 7bea168f7920
Revises: 
Create Date: 2025-10-17 00:12:52.902539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bea168f7920'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='配置类型：global全局,template模板'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置描述'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('workflow_type', sa.String(length=32), nullable=False, comment='工作流类型'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态码：0待处理,1处理中,2成功,3失败,4跳过,5取消,6部分完成'),
    sa.Column('params', sa.JSON(), nullable=True, comment='任务参数JSON'),
    sa.Column('result', sa.JSON(), nullable=True, comment='任务结果JSON'),
    sa.Column('error_msg', sa.String(length=255), nullable=True, comment='错误信息'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联任务ID'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='分镜序号'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态码：0待处理,1处理中,2成功,3失败,4跳过,5取消'),
    sa.Column('params', sa.JSON(), nullable=True, comment='分镜参数JSON'),
    sa.Column('result', sa.JSON(), nullable=True, comment='分镜结果JSON'),
    sa.Column('error_msg', sa.String(length=255), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联任务ID'),
    sa.Column('step_name', sa.String(length=64), nullable=False, comment='步骤名称'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='步骤顺序'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态码：0待处理,1处理中,2成功,3失败,4跳过,5取消'),
    sa.Column('params', sa.JSON(), nullable=True, comment='步骤参数JSON'),
    sa.Column('result', sa.JSON(), nullable=True, comment='步骤结果JSON'),
    sa.Column('error_msg', sa.String(length=255), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联任务ID'),
    sa.Column('scene_id', sa.Integer(), nullable=True, comment='关联分镜ID'),
    sa.Column('file_type', sa.String(length=16), nullable=False, comment='文件类型：image,audio,video'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='本地文件路径'),
    sa.Column('file_url', sa.String(length=255), nullable=True, comment='远程文件URL'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=64), nullable=True, comment='MIME类型'),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='元数据JSON'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='关联任务ID'),
    sa.Column('step_id', sa.Integer(), nullable=True, comment='关联步骤ID'),
    sa.Column('scene_id', sa.Integer(), nullable=True, comment='关联分镜ID'),
    sa.Column('log_type', sa.String(length=16), nullable=False, comment='日志类型：info,warning,error'),
    sa.Column('message', sa.Text(), nullable=False, comment='日志信息'),
    sa.Column('stack_trace', sa.Text(), nullable=True, comment='错误堆栈'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['task_steps.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_logs')
    op.drop_table('files')
    op.drop_table('task_steps')
    op.drop_table('scenes')
    op.drop_table('tasks')
    op.drop_table('config')
    # ### end Alembic commands ###
